### ISSUE TITLE
Provide documentation for queue.xml

### ISSUE THREAD

**Issue by rahulsom** [kdabir/glide#36]
Task queues are useful for certain kinds of apps. It would be nice to document where features such as task queues, cron actions, etc. go in a glide app.

**Comment by kdabir** [comment]
Yeah, I agree, i have been slacking on documenting the entire stuff. Partly the reason was i thought i'd come up with a better DSL. But then it poses problem of updating the DSL whenever a new feature is added by google to the underlying XML. another way is to just let end user code in MarkupBuilder so xml is less painful.


Anyways this is how my current glide.groovy looks like (with queue and cron config):

```groovy
app {
    name = "my-app"
    version = "1"
}

queue {
    total_storage_limit = "10M"

    entries = [
            [
                    name                   : 'fetch-list',
                    rate                   : '1/m',
                    retry_parameters       : [task_retry_limit: 3],
                    max_concurrent_requests: 1
            ],
            [
                    name                   : 'fetch-details',
                    rate                   : '1/m',
                    retry_parameters       : [task_retry_limit: 3],
                    max_concurrent_requests: 1
            ]
    ]
}

cron {
    entries = [
            [url:"/cron.groovy", description:"trigger processing", schedule:"every 21 minutes"],
    ]
}

```

But i really want to change that. and document it too. Also the latest glide honors your own queue.xml/cron.xml if you put that in WEB-INF, glide won't overwrite them. Hope that helps

**Comment by rahulsom** [comment]
Thanks! That is awesome.
